import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <link rel="manifest" href="/manifest.json" />

      {/* Hide overflow to disable pull-to-refresh */}
      <body className="mx-auto max-w-sm overflow-y-hidden">
        <main>{children}</main>
      </body>
    </html>
  );
}
